
CREATE TABLE IF NOT EXISTS BASE.USER(
	USER_ID INTEGER NOT NULL DEFAULT NEXTVAL('BASE.USER_USER_ID'::regclass),
	USER_NAME character varying(100) NOT NULL,
	LOGIN_ID character varying(100),
	PASSWORD character varying(100),
	EMAIL_ID character varying(100),
	PHONE_NO character varying(100),
	VALID_FROM_DT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	VALID_TO_DT TIMESTAMP WITH TIME ZONE,
	ACCOUNT_LOCKED BOOLEAN DEFAULT FALSE,
	ACTIVE BOOLEAN,
	ORG_CODE character varying(50) NOT NULL,
	BRANCH_CODE character varying(50) NOT NULL,
	LAST_LOGIN TIMESTAMP WITH TIME ZONE,
	USER_TYPE character varying(100),
	ALLOW_LOGIN BOOLEAN DEFAULT FALSE, -- FOR SMS 	
	LOGIN_FAILED_COUNT INTEGER DEFAULT 0,
	IS_SUPER_USER BOOLEAN DEFAULT FALSE,
	CONSTRAINT USER_ID_PKEY PRIMARY KEY(USER_ID),
	CONSTRAINT LOGIN_ID_UK UNIQUE(LOGIN_ID),
	CONSTRAINT org_code_fk FOREIGN KEY (org_code)
    	REFERENCES base.organization (org_code),
	CONSTRAINT BRANCH_code_fk FOREIGN KEY (BRANCH_CODE)
    	REFERENCES base.BRANCH (BRANCH_CODE)
	
);